name: BuildCore CI

on:
  push:
    branches: [main]
    tags: ["*"]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build Arm32/64 Core
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install ECCLL
      run: |
        wget -q "http://ellcc.org/releases/latest/ellcc-x86_64-linux-2017-08-23.bz2" -O temp.bz2
        bunzip2 temp.bz2
        tar xf temp
        cd ellcc
        ./ellcc install
        ./ellcc install libraries
        cd ..
    
    - name: Build Arm64
      run: ./ellcc/bin/ecc++ -target arm64v8-linux main.cpp md5-c.cpp -o miner-arm64 -std=c++17 -lpthread -O3 -static
    
    - name: Build Arm32
      run: ./ellcc/bin/ecc++ -target arm32v7-linux main.cpp md5-c.cpp -o miner-arm32 -std=c++17 -lpthread -O3 -static

    - name: Upload Binaries
    - uses: actions/upload-artifact@v3
      with:
        name: MinerBinaries
        path: ./miner-*
